myproject/core/urls.py
from django.urls import include, path
from myproject.core import views as v


app_name = 'core'


url_coreui = [
    path('dashboard/', v.dashboard, name='dashboard'),
    path('breadcrumb/', v.breadcrumb, name='breadcrumb'),
    path('cards/', v.cards, name='cards'),
    path('carousel/', v.carousel, name='carousel'),
    path('collapse/', v.collapse, name='collapse'),
    path('forms/', v.forms, name='forms'),
    path('jumbotron/', v.jumbotron, name='jumbotron'),
    path('list_group/', v.list_group, name='list_group'),
    path('navs/', v.navs, name='navs'),
    path('pagination/', v.pagination, name='pagination'),
    path('popovers/', v.popovers, name='popovers'),
    path('progress/', v.progress, name='progress'),
    path('scrollspy/', v.scrollspy, name='scrollspy'),
    path('switches/', v.switches, name='switches'),
    path('tables/', v.tables, name='tables'),
    path('tabs/', v.tabs, name='tabs'),
    path('tooltips/', v.tooltips, name='tooltips'),
    path('brand_buttons/', v.brand_buttons, name='brand_buttons'),
    path('button_group/', v.button_group, name='button_group'),
    path('buttons/', v.buttons, name='buttons'),
    path('dropdowns/', v.dropdowns, name='dropdowns'),
    path('charts/', v.charts, name='charts'),
    path('colors/', v.colors, name='colors'),
    path('coreui_icons/', v.coreui_icons, name='coreui_icons'),
    path('flags/', v.flags, name='flags'),
    path('font_awesome/', v.font_awesome, name='font_awesome'),
    path('simple_line_icons/', v.simple_line_icons, name='simple_line_icons'),
    path('login/', v.login, name='login'),
    path('alerts/', v.alerts, name='alerts'),
    path('badge/', v.badge, name='badge'),
    path('modals/', v.modals, name='modals'),
    path('register/', v.register, name='register'),
    path('typography/', v.typography, name='typography'),
    path('widgets/', v.widgets, name='widgets'),
    path('404/', v.error404, name='error404'),
    path('500/', v.error500, name='error500'),
    path('invoice/', v.invoice, name='invoice'),
]


urlpatterns = [
    path('', v.index, name='index'),
    path('list/', v._list, name='list'),
    path('detail/', v._detail, name='detail'),
    path('add/', v._create, name='create'),
    path('coreui/', include(url_coreui)),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin
urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

myproject/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)


def _list(request):
    template_name = '_list.html'
    return render(request, template_name)


def _detail(request):
    template_name = '_detail.html'
    return render(request, template_name)


def _create(request):
    template_name = '_form.html'
    return render(request, template_name)


def dashboard(request):
    template_name = 'dashboard.html'
    return render(request, template_name)


def breadcrumb(request):
    template_name = 'base/breadcrumb.html'
    return render(request, template_name)


def cards(request):
    template_name = 'base/cards.html'
    return render(request, template_name)


def carousel(request):
    template_name = 'base/carousel.html'
    return render(request, template_name)


def collapse(request):
    template_name = 'base/collapse.html'
    return render(request, template_name)


def forms(request):
    template_name = 'base/forms.html'
    return render(request, template_name)


def jumbotron(request):
    template_name = 'base/jumbotron.html'
    return render(request, template_name)


def list_group(request):
    template_name = 'base/list-group.html'
    return render(request, template_name)


def navs(request):
    template_name = 'base/navs.html'
    return render(request, template_name)


def pagination(request):
    template_name = 'base/pagination.html'
    return render(request, template_name)


def popovers(request):
    template_name = 'base/popovers.html'
    return render(request, template_name)


def progress(request):
    template_name = 'base/progress.html'
    return render(request, template_name)


def scrollspy(request):
    template_name = 'base/scrollspy.html'
    return render(request, template_name)


def switches(request):
    template_name = 'base/switches.html'
    return render(request, template_name)


def tables(request):
    template_name = 'base/tables.html'
    return render(request, template_name)


def tabs(request):
    template_name = 'base/tabs.html'
    return render(request, template_name)


def tooltips(request):
    template_name = 'base/tooltips.html'
    return render(request, template_name)


def brand_buttons(request):
    template_name = 'buttons/brand-buttons.html'
    return render(request, template_name)


def button_group(request):
    template_name = 'buttons/button-group.html'
    return render(request, template_name)


def buttons(request):
    template_name = 'buttons/buttons.html'
    return render(request, template_name)


def dropdowns(request):
    template_name = 'buttons/dropdowns.html'
    return render(request, template_name)


def charts(request):
    template_name = 'charts.html'
    return render(request, template_name)


def colors(request):
    template_name = 'colors.html'
    return render(request, template_name)


def coreui_icons(request):
    template_name = 'icons/coreui-icons.html'
    return render(request, template_name)


def flags(request):
    template_name = 'icons/flags.html'
    return render(request, template_name)


def font_awesome(request):
    template_name = 'icons/font-awesome.html'
    return render(request, template_name)


def simple_line_icons(request):
    template_name = 'icons/simple-line-icons.html'
    return render(request, template_name)


def alerts(request):
    template_name = 'notifications/alerts.html'
    return render(request, template_name)


def badge(request):
    template_name = 'notifications/badge.html'
    return render(request, template_name)


def modals(request):
    template_name = 'notifications/modals.html'
    return render(request, template_name)


def typography(request):
    template_name = 'typography.html'
    return render(request, template_name)


def widgets(request):
    template_name = 'widgets.html'
    return render(request, template_name)


def login(request):
    template_name = 'login.html'
    return render(request, template_name)


def register(request):
    template_name = 'register.html'
    return render(request, template_name)


def error404(request):
    template_name = '404.html'
    return render(request, template_name)


def error500(request):
    template_name = '500.html'
    return render(request, template_name)


def invoice(request):
    template_name = 'invoice.html'
    return render(request, template_name)

myproject/core/templates/includes/breadcrumb.html
<!-- Breadcrumb-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'core:index' %}">Home</a>
  </li>
  <li class="breadcrumb-item">
    <a href=".">List</a>
  </li>
  <li class="breadcrumb-item active">Dashboard</li>
  <!-- Breadcrumb Menu-->
  <li class="breadcrumb-menu d-md-down-none">
    <div class="btn-group" role="group" aria-label="Button group">
      <a class="btn" href="">
        <i class="icon-speech"></i>
      </a>
      <a class="btn" href="{% url 'core:index' %}">
        <i class="icon-graph"></i>  Dashboard</a>
      <a class="btn" href="">
        <i class="icon-settings"></i>  Settings</a>
    </div>
  </li>
  {% block breadcrumb %}{% endblock breadcrumb %}
</ol>

myproject/core/templates/includes/navbar.html
{% load static %}
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'core:index' %}">
    <img class="navbar-brand-full" src="{% static 'img/brand/logo.svg' %}" width="89" height="25" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="{% static 'img/brand/sygnet.svg' %}" width="30" height="30" alt="CoreUI Logo">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
      <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="#">Users</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="#">Settings</a>
    </li>
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
        <span class="badge badge-pill badge-danger">5</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 notifications</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="icon-user-follow text-success"></i> New user registered</a>
        <a class="dropdown-item" href="#">
          <i class="icon-user-unfollow text-danger"></i> User deleted</a>
        <a class="dropdown-item" href="#">
          <i class="icon-chart text-info"></i> Sales report is ready</a>
        <a class="dropdown-item" href="#">
          <i class="icon-basket-loaded text-primary"></i> New client</a>
        <a class="dropdown-item" href="#">
          <i class="icon-speedometer text-warning"></i> Server overloaded</a>
        <div class="dropdown-header text-center">
          <strong>Server</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>CPU Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">348 Processes. 1/4 Cores.</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>Memory Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">11444GB/16384MB</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>SSD 1 Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">243GB/256GB</small>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-list"></i>
        <span class="badge badge-pill badge-warning">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 pending tasks</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Upgrade NPM &amp; Bower
            <span class="float-right">
              <strong>0%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">ReactJS Version
            <span class="float-right">
              <strong>25%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">VueJS Version
            <span class="float-right">
              <strong>50%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Add new layouts
            <span class="float-right">
              <strong>75%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Angular 2 Cli Version
            <span class="float-right">
              <strong>100%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all tasks</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-envelope-letter"></i>
        <span class="badge badge-pill badge-info">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 4 messages</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-success"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">Just now</small>
            </div>
            <div class="text-truncate font-weight-bold">
              <span class="fa fa-exclamation text-danger"></span> Important message</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-warning"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">5 minutes ago</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-danger"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">1:52 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-info"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">4:03 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all messages</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="avatar">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Account</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-bell-o"></i> Updates
          <span class="badge badge-info">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-envelope-o"></i> Messages
          <span class="badge badge-success">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-tasks"></i> Tasks
          <span class="badge badge-danger">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-comments"></i> Comments
          <span class="badge badge-warning">42</span>
        </a>
        <div class="dropdown-header text-center">
          <strong>Settings</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-user"></i> Profile</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-wrench"></i> Settings</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-usd"></i> Payments
          <span class="badge badge-secondary">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-file"></i> Projects
          <span class="badge badge-primary">42</span>
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-shield"></i> Lock Account</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-lock"></i> Logout</a>
      </div>
    </li>
  </ul>
  <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
    <span class="navbar-toggler-icon"></span>
  </button>
</header>

myproject/core/templates/includes/sidebar.html
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:dashboard' %}">
          <i class="nav-icon icon-speedometer"></i> Dashboard
          <span class="badge badge-primary">NEW</span>
        </a>
      </li>
      <li class="nav-title">Theme</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:colors' %}">
          <i class="nav-icon icon-drop"></i> Colors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:typography' %}">
          <i class="nav-icon icon-pencil"></i> Typography</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:list' %}">
          <i class="nav-icon icon-list"></i> List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:detail' %}">
          <i class="nav-icon icon-book-open"></i> Detail</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:create' %}">
          <i class="nav-icon icon-puzzle"></i> Add</a>
      </li>
      <li class="nav-title">Components</li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-puzzle"></i> Base</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:breadcrumb' %}">
              <i class="nav-icon icon-puzzle"></i> Breadcrumb</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cards' %}">
              <i class="nav-icon icon-puzzle"></i> Cards</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:carousel' %}">
              <i class="nav-icon icon-puzzle"></i> Carousel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:collapse' %}">
              <i class="nav-icon icon-puzzle"></i> Collapse</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:forms' %}">
              <i class="nav-icon icon-puzzle"></i> Forms</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:jumbotron' %}">
              <i class="nav-icon icon-puzzle"></i> Jumbotron</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_group' %}">
              <i class="nav-icon icon-puzzle"></i> List group</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:navs' %}">
              <i class="nav-icon icon-puzzle"></i> Navs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:pagination' %}">
              <i class="nav-icon icon-puzzle"></i> Pagination</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:popovers' %}">
              <i class="nav-icon icon-puzzle"></i> Popovers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:progress' %}">
              <i class="nav-icon icon-puzzle"></i> Progress</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:scrollspy' %}">
              <i class="nav-icon icon-puzzle"></i> Scrollspy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:switches' %}">
              <i class="nav-icon icon-puzzle"></i> Switches</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:tables' %}">
              <i class="nav-icon icon-puzzle"></i> Tables</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:tabs' %}">
              <i class="nav-icon icon-puzzle"></i> Tabs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:tooltips' %}">
              <i class="nav-icon icon-puzzle"></i> Tooltips</a>
          </li>
        </ul>
      </li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-cursor"></i> Buttons</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:buttons' %}">
              <i class="nav-icon icon-cursor"></i> Buttons</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:button_group' %}">
              <i class="nav-icon icon-cursor"></i> Buttons Group</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:dropdowns' %}">
              <i class="nav-icon icon-cursor"></i> Dropdowns</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:brand_buttons' %}">
              <i class="nav-icon icon-cursor"></i> Brand Buttons</a>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:charts' %}">
          <i class="nav-icon icon-pie-chart"></i> Charts</a>
      </li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-star"></i> Icons</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:coreui_icons' %}">
              <i class="nav-icon icon-star"></i> CoreUI Icons
              <span class="badge badge-success">NEW</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:flags' %}">
              <i class="nav-icon icon-star"></i> Flags</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:font_awesome' %}">
              <i class="nav-icon icon-star"></i> Font Awesome
              <span class="badge badge-secondary">4.7</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:simple_line_icons' %}">
              <i class="nav-icon icon-star"></i> Simple Line Icons</a>
          </li>
        </ul>
      </li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-bell"></i> Notifications</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:alerts' %}">
              <i class="nav-icon icon-bell"></i> Alerts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:badge' %}">
              <i class="nav-icon icon-bell"></i> Badge</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:modals' %}">
              <i class="nav-icon icon-bell"></i> Modals</a>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:widgets' %}">
          <i class="nav-icon icon-calculator"></i> Widgets
          <span class="badge badge-primary">NEW</span>
        </a>
      </li>
      <li class="divider"></li>
      <li class="nav-title">Extras</li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-star"></i> Pages</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:login' %}" target="_top">
              <i class="nav-icon icon-star"></i> Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:register' %}" target="_top">
              <i class="nav-icon icon-star"></i> Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:error404' %}" target="_top">
              <i class="nav-icon icon-star"></i> Error 404</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:error500' %}" target="_top">
              <i class="nav-icon icon-star"></i> Error 500</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:invoice' %}" target="_top">
              <i class="nav-icon icon-star"></i> Invoice</a>
          </li>
        </ul>
      </li>
      <li class="nav-item mt-auto">
        <a class="nav-link nav-link-success" href="https://coreui.io" target="_top">
          <i class="nav-icon icon-cloud-download"></i> Download CoreUI</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-danger" href="https://coreui.io/pro/" target="_top">
          <i class="nav-icon icon-layers"></i> Try CoreUI
          <strong>PRO</strong>
        </a>
      </li>
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>